// import JSONData from "./products.json";

function GetHomePage() {
  let headersList = {
    authority: "www.vinted.co.uk",
    path: "/api/v2/users/59783356/items?page=1&per_page=20&order=relevance¤cy=GBP",
    accept: "application/json, text/plain, */*",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en - uk - fr",
    "cache-control": "no-cache",
    cookie:
      "__cf_bm=Th23D9nqULaxcSKBoTN2jR6zrQrGU1CwiJfy0TdOYfw-1631343532-0-ASR1drOTz/j0RGVgPrcz6CK7FvIO6Wmso99fdZfVot7yoh3Y9S4kCoj2MImmQx6nAuR0FI5ubvlP3yNZlFVCoQhIG44FCV7+UAoHhvnGf20i; anon_id=c5725f65-8f74-492f-85ec-263e9672d717; G_ENABLED_IDPS=google; OptanonAlertBoxClosed=2021-09-11T06:58:58.266Z; eupubconsent-v2=CPMW0TFPMW0TFAcABBENBmCsAP_AAAAAAChQIJNf_X9fb2vj-_599_t0eY1f9_63t-wzjheNs-8NyZ_X_J4Xv2MyvB34pqYKmR4EunLBAQdlHGHcTQgAwIkVqTLsYk2MjzNKJ7JEmhMbe2dYGH9vn8XT-ZKY70-v___7v3-_____7pAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH_9AAAAkEASAACgAcAB4AFwAWgA-ACMAEkAMQAfwBIgDNAG0AOIAcgA5wB1AD_AIOAT8AoYBhADRAIfAR6AlYBNoCwgF0ALqAXaAvIBiADFgGQgMjAZQEgnAAIAAXABQAFQAMgAcgA8AEAAIgAZQA0ADUAHkAQwBFACYAE-AKoArABYADeAHMAPQAfgBCACGgEQARIAjgBLACaAFKALcAYYAyABlwDUANUAbIA7wB7AD4gH2AfoBAACBwEXARgAjQBHACUgFLAKuAXMAvwBigDWAG0ANwAbwA9AB8gENgIvASIAmIBMoCbAE7AKHAUiApoBYoC0AFsALkAXeAvMBgQDBgGEgMNAYeAyIBkgDJwGXBgCAACwALgBGACSAGIAN4ApABpADVAHEAS0A6gChwFiAL6AZGGgOABWAC4AIYAZAAywBqADZAH4AQAAjABSwCrwFoAWkA1gBvAD5AIqAReAkQBNgCdgFIgLkAYEAwkBh4DGAGTiABgACwALgBGACSAGIAN4ApABqgDiAJaAbwBQ4iAuAFYAQwAyABlgDUAGyAPwAgABGAClgFXANYAfIBF4CRAE2AJ2AUiAuQBgQDCQGHgMnFQGAAKABDACYAFwARwAywBqAD8AIwARwApYBV4C0ALSAbwBIICYgE2AKbAWwAuQBeYDAgGHgMiFACwAxACkAGqANoAcQA5AB4AEtAR6AsQBfQyAsABQAIYATABHADLAGpAPsA_ACMAEcAKWAVcArYBvAEnAJiATYAtEBbAC8wGBAMPAZEMAGABiAFIANUAbQA4gByADwAJaAWIBHoCxAF5DgIwAAgAEQAOAA8AC4ALQAcgA_ACCAEYAMgAaAA_gCRAFIALMAZYAzQBpADVAG0AOIAcgA5wB1ADuAIBAQcBCACIgEtAJtAT4BPwClgFQALbAYABgQDCAGZANYAa8A3gBxwDpAHkAPkAhCBD4EQAI9gSsBK4CYgEygJtAUKApABSYCmAFTAKqAVsArkBXYCygFxQLoAuoBewC-gGBAMQAYsAyEBlA6C2AAuACgAKgAZAA5AB8AIAARQAxADKAGgAagA8AB9AEMARQAmABPgCqAKwAWIAuAC6AF8AMQAZgA3gBzAD0AH4AQgAhoBEAESAI4ASwAmABNACjAFKALEAW8AwgDDAGQAMoAaIA1ABsgDfAHeAPaAfYB-gD_AIHARYBGACOAEpAKuAWKAtAC0gFzALqAXkAvwBigDaAG4gOmA6gB6AENgIiARUAi8BIICRAEyAJsATsAocBTQCrAFigLQgWwBbIC4AFyALtAXeAvMBgwDCQGGgMPAYkAxgBjwDJAGTgMuIAJQAEAA_ACCAGgAP4AkQBSAC3AGWANUAbQA4gByADnAHgAT4ApYBYgDAAGEAMyAbwA7YCHwEegJXATEAm0BQoCkAFJgK2AXQAvIBewC-gGBEIGYACwAKAAZABEADEAIYATAApgBVAC4AF8AMQAZgA3gB6AEcALEAYQAygBqADfAHfAPsA_AB_gEYAI4ASkAoYBV4C0ALSAXMAvwBigDaAHUAPQAkEBIgCTgE2AKaAWKAtGBbAFtALgAXIAu0Bh4DEgGRAMnJAIQABAAOAAuACEAHIAZAA3gCRAFIALkAXwAywBqADaAHcAQAAhIBLQCfAFQAMyAa8A3gB9gEegJWATaApMBZQC6AF7AL6AYsSgYgAIAAWABQADIAHAARAAxAB4AEQAJgAVQAuABfADEAGYANoAhABDQCIAIkARwAowBSgC3AGEAMoAaoA2QB3gD8AIwARwAq8BaAFpALqAYoA3AB1AD5AIqAReAkQBNgCxQFsALtAXmAw8BkQDJygDcAAQAFwAQgA5AB-AEYAKwAZAA2gBvAEcAJEAUgAuQBlgDUAGuANoAcQA5wB1ADuAHgAQAAg4BCQCKgEiAJaATYAncBPgE_AKWAWIAuoBgADCAGvAN4AdsA8gB_wEegJiATKAm0BSACmAFTAK7AXQAvIBfQDAgGLFIIYAC4AKAAqABkADkAHwAgABFADEAMoAaABqADyAIYAigBMACeAFIAKoAWAAvgBiADMAHMAPwAhABDQCIAIkAUYApQBYgC3AGEAMoAaIA1QBsgDvgH2AfoBFgCMAEcAJSAUMAq4BWwC5gF5AMUAbQA3AB6AEXgJEAScAmwBOwChwFigLQAWwAuABcgC7QF5gMNAYeAxgBkQDJAGTgMu.f_gAAAAAAAAA; domain_selected=true; G_AUTHUSER_H=0; seller_header_visits=2; feature.expose.c5725f65-8f74-492f-85ec-263e9672d717=%5B%22sqp_ads%22%2C%22unsuccessful_seller_boost_weight%22%2C%22content_autotranslation%22%2C%22gdpr_store_card_details%22%2C%22nasa_delivery_instructions_redesign%22%5D; _vinted_fr_session=dE56d2Yyem4vYXJpL09mSXNma2JSOGduMFFITnViRUxFMTJSRXFZdFFNSGtiZmwyOHJRemRjR0JqS2xsVzBqRThvV09vQW5FSjZxQ3FlYnRPNVpCWFJLYWduTUQ4Z0lxd1JaYTcwOW1QWWphUmF3VkxVRGd6cThkVm5VQVJDbm8rYlh2K3B6WVVERUlYSkFBSlNRMG1QRlF6OWdJWVN6Q1ZpNXBHTktod2RFTUFhNWN5NUNKenM0cC9neVVoWlZFNitENHZCUU4xTnRvS2Q5aFhmU1VGMms1ckd3K1ByZmVFcXh1MU5NRWhzUWwxK3JGKzZ5V2NTSC9MVmwzbVFvZzVudjdqWkVCL2R2Y3J0dGdJOHlqQXdUNnJCbEdYY1VzZ3ZMK1JkM1NDSTZhaFduM3oyNHFzUVZFK1lLQ29ZSWJmNHBsQUtYSEJLU29rbFcrYXJrWGpZQUJNaEhaREtMRkIyNUN4dDdBUGUwd3FlUElXNDFRN0tCWGRmTDFqZ1pLVWpuOVZGSUVVdFFscHpaVnFJS2FQbWQ1VnZPRWFRSkwrdzhhc0g4bnBOSy9vcDhDZnBrNk1CRlcxVzVPZ1RyOGduNzhrSWw4M0RlTUNHZElvenZ2dGxVZHJOTmIyMUQvQnNEYXNiNWV5ZzRLUnJQUDNMMlkwQ0duVmRPS1g5MURZRkdRenU4Vm1iTWR6bS9xUHphcE1uTmRtQkhDeTlCQWtxN1VKTnZaTjEydjRZY2NVMWJ6SG5xWWRrSk9jTWQ0Z3BqTXIzc3Q3djA3d2IrYStTY1RKR1RETURqZjAvRXZtWDE5ZlRmdFg5eHp1RW9rYkpVWkx4RXdIRWhWaG0yK25Db2d1NnhDMkJZd0FVSU1PQmpwd2RSbTFsOWVnbHR0enVDSFMwdmdwTnZjTlZwTmIxSGFQbkNsMStzVTkyd0VzTnFBR0RZZnJTT2lOamNyVUJpR3l1S3ozNzFCRW1PWUZjMjdxaVFtMHBhazJFdzl4UDdIYmFndDB1VVNsNG1jVUpJbHRDRUpWY3FNeUw5RzY0S0NjdTUyTmtvYTU3UEJzOTJBRUR2SUVENTRWTVY0QjgwWVN3R1ZoUHBxelpMZVNVZk9oTTVqTTFIaE5NRlhVQlA4ZnQ2REwxVFkvTjJrc0VqVTNBS2dCWjdPVCtwYmlvcXIybThaeVFEZG1qQU1nYmFNeklVVmNWMnQwb2pqaExMajRsQitmK2tEbDFKQkZ4NEhPUFRyc2srUVlCOEFQWUZrck1tWFNkODFGVmowaDF4QkRwWlhsdG94YWNmWlBtd09nUUZmRnhYUTh4aDk5ODZwUmJBNVRZU2d6SXExdHpZL0o4YTM3RWU5VkJ3eUIzS25NS1NyaEpIYkRzaVQwM2tkSFYySkJNNEpxWEFSTlJWWFdyOVJYVFNwcFd0dHg5c2NNMFVJODdSL1l1RXE3TktNb1VwVDBieWwzWDRvamFMZFhDdDNsQ3pLL21pMDFoYlBNRHpJQzB3WC84ZkdEb21RWmxQTGJ6T3FLWFpmSnNBQTBlN0R4OUJuTGh3VFRoUWtaaHBOUlRtbERwaHFiaWNBQjdQMCtsUUkxSnJJRTNJeXRRN0pvaWR4U28velFQNFhoN3JvcWpBbnkySXJudU5weVJmMTN4STA3M3NpOUVKcDR4a0VrNUt3eFJlOXU4VUx4LzhtOCtOWEJPdkg4VHdrSzNpcXA1WmZKT3U3ZnJibjQwNkVGMVY2Y1hWUHJOeEhiMmNialpNPS0tWm5sd1RiUGNUY2ZMVHZhTXdaMXU4dz09--25438b1cb0f6b84eaf81d6d2174e929940770f6c; OptanonConsent=isGpcEnabled=0&datestamp=Sat+Sep+11+2021+11%3A19%3A35+GMT%2B0400+(Gulf+Standard+Time)&version=6.20.0&isIABGlobal=false&hosts=&consentId=126a29dc-68d4-4c92-835c-7fc3187d57e7&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1%2CSTACK42%3A1&geolocation=AE%3BDU&AwaitingReconsent=false",
    pragma: "no - cache",
    referer: "https://www.vinted.co.uk/member/59783356-lessthanten",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "Windows",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent":
      "Mozilla 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36",
    "x-csrf-token":
      "_lRgrfYJ2Lkxf3HeeTAbnMHqx3vkunfkyemQ6EGFgVgs9RsT9L6n6OcQeh97IQwDEUqYOxerQDc4Gyf4T2MKog",
  };

  fetch("https://www.vinted.co.uk/member/59783356-lessthanten", {
    method: "GET",
    headers: headersList,
  })
    .then(function (response) {
      return response.text();
    })
    .then(function (data) {
      console.log(data);
    });
}

async function FetchJSON() {
  let headersList = {
    Accept: "*/*",
    "User-Agent": "www.vinted.co.uk",
    // "x-csrf-token":
    //   "cypXEJPGZtYMVf9UyexNzYXve-NduxqSduuhWt_1Iq6hiyyukXEZh9o69JXL_VpSVU8ko66qLUGHGRZK0ROpVA",
    Referer: "https://www.vinted.co.uk/member/59783356-lessthanten",
    // "Access-Control-Allow-Headers": "*",
  };
  const myData = await fetch(
    `https://api.allorigins.win/get?url=${encodeURIComponent(
      "https://www.vinted.co.uk/api/v2/users/59783356/items?page=1&per_page=20&order=relevance¤cy=GBP/"
    )}`,

    {
      method: "GET",
      headers: headersList,
    }
  );

  const TheData = await myData.json();
  console.log(TheData);
}

FetchJSON();
